apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
namespace: react
images:
  - name: kubernetes-argocd-react
    newName: kubernetes-argocd-react
    newTag: v1
